name: Build

on:
 workflow_dispatch:
 push:
   branches:
     - main
 
defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --distpath dist/twitchcollabnetwork/${{ matrix.os }}/ --name=twitchcollabnetwork-${{ matrix.os }} main.py

      - name: Copy Resources
        run: mkdir dist/twitchcollabnetwork/${{ matrix.os }}/templates && cp templates/* dist/twitchcollabnetwork/${{ matrix.os }}/templates/

      - name: Copy Config
        run: cp config.ini dist/twitchcollabnetwork/${{ matrix.os }}/config.ini

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twitchcollabnetwork-${{ matrix.os }}
          path: dist/twitchcollabnetwork/${{ matrix.os }}/twitchcollabnetwork-${{ matrix.os }}*
          if-no-files-found: error
