name: Build

on:
 workflow_dispatch:
 push:
   tags:
     - "v*.*.*"
   branches:
     - main
 
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --distpath dist/twitchcollabnetwork/${{ matrix.os }}-${{github.ref_name}}/ --collect-data pyvis --name=twitchcollabnetwork-${{ matrix.os }}-${{github.ref_name}} main.py

      - name: Copy Resources
        run: mkdir dist/twitchcollabnetwork/${{ matrix.os }}-${{github.ref_name}}/templates && cp templates/* dist/twitchcollabnetwork/${{ matrix.os }}-${{github.ref_name}}/templates/

      - name: Copy Config
        run: cp config.ini dist/twitchcollabnetwork/${{ matrix.os }}-${{github.ref_name}}/config.ini

      - name: Deploy Artifacts
        uses: actions/upload-artifact@v4
        if: true && !startsWith(github.ref, 'refs/tags/')
        with:
          name: twitchcollabnetwork-${{matrix.os}}-latest
          path: dist/twitchcollabnetwork/${{matrix.os}}-${{github.ref_name}}/
          if-no-files-found: error

      - name: Release Rename
        if: startsWith(github.ref, 'refs/tags/') && ${{matrix.os}} != 'windows'
        run: zip -r twitchcollabnetwork-${{matrix.os}}-${{github.ref_name}}.zip dist/twitchcollabnetwork/${{matrix.os}}-${{github.ref_name}}

      - name: Release Rename - Windows
        if: startsWith(github.ref, 'refs/tags/') && ${{matrix.os}} == 'windows'
        run: Compress-Archive -Path dist/twitchcollabnetwork/${{matrix.os}}-${{github.ref_name}} -Destination twitchcollabnetwork-${{matrix.os}}-${{github.ref_name}}.zip

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.TCN_GITHUB_TOKEN }}
          files: twitchcollabnetwork-${{matrix.os}}-${{github.ref_name}}.zip